name: srclib_dart
author: adam singer
description:  Something
dependencies:
  args: '>=0.9.0 <0.13.0'
  logging: '>=0.9.0 <0.10.0'
  markdown: 0.7.0
  path: '>=0.9.0 <2.0.0'
  yaml: '>=0.9.0 <3.0.0'
  compiler_unsupported: ">=0.7.2 <0.8.0"
dev_dependencies:
  scheduled_test: '>=0.10.0 <0.12.0'
  unittest: '>=0.9.0 <0.11.0'

