name: srclib_dart
author: Adam Singer <financeCoding@gmail.com>
description: dart toolchain for srclib.org
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  analyzer: '>=0.22.2 <0.23.0'
  args: '>=0.9.0 <0.13.0'
  logging: '>=0.9.0 <0.10.0'
  markdown: 0.7.0
  path: '>=0.9.0 <2.0.0'
  yaml: '>=0.9.0 <3.0.0'
  compiler_unsupported: '>=0.7.2 <0.8.0'
  watcher: '>=0.9.0 <0.10.0'

dev_dependencies:
  scheduled_test: '>=0.10.0 <0.12.0'
  unittest: '>=0.9.0 <0.12.0'
  typed_mock: '>=0.0.4 <1.0.0'
